name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"   # nightly run at midnight

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Smoke Suite
        run: npx playwright test --grep "@smoke" --reporter=html

      - name: Run Sanity Suite
        run: npx playwright test --grep "@sanity" --reporter=html

      - name: Run Regression Suite
        run: npx playwright test --grep "@regression" --reporter=html

      - name: Run Negative Suite
        run: npx playwright test --grep "@negative" --reporter=html

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
